#!/bin/sh
# Copyright (C) 2014 Benjamin Chrétien <chretien@lirmm.fr>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

YAD_CAL_CLASS="YADWIN_CALENDAR"

kill_calendar() {
  # Kill any existing yad calendar
  if [[ -n "$1" ]]; then
    kill $1
  fi
}

display_calendar() {
  # Display the calendar with yad at the right position
  eval $(xdotool getmouselocation --shell) &>/dev/null
  yad --no-buttons --geometry=+$(($X-300))+20 \
      --class ${YAD_CAL_CLASS} --calendar & &>/dev/null
}

toggle_calendar() {
  # Calendar PID
  CAL_PID=$(xdotool search --class ${YAD_CAL_CLASS} getwindowpid)

  # If there's already a calendar process
  if [[ -n "$CAL_PID" ]]; then
    kill_calendar $CAL_PID
  else
    display_calendar
  fi
}

case $BLOCK_BUTTON in
    # Get mouse position then display calendar with yad
    [1-5]) toggle_calendar ;;
esac

date '+%d/%m/%Y %H:%M'
