#!/usr/bin/env bash

cfg_tmpdir="/tmp/$USER"

err() { echo "$*" >&2; }

usage() {
	while read; do printf '%s\n' "$REPLY"; done <<- EOF
		Usage: i3lock-extra <-m mode> [args]
		Modes:
		       rnd <dir>        # Use a random image from a dir.
		       blur [img]       # Take a screenshot, blur it out. If provided, add an image on top.
		       pixelize [img]   # Same as the abobe, but pixelize the image instead.
		       img <img>        # Use the provided image.

		For more information: https://www.reddit.com/r/unixporn/comments/3358vu/i3lock_unixpornworthy_lock_screen/cqknntb
	EOF
}

random() {
	images_dir=$1

	images=( "$images_dir"/* )
	images_c="${#images[*]}"
	image_r=$(( RANDOM % images_c ))
	image="${images[$image_r]}"

	printf '%s' "$image"
}

deskshot() {
	declare dist_mode=$1; shift

	bg_image="${cfg_tmpdir}/lockbg.png"
	case "${dist_mode:-pixelize}" in
		blur) grim "${bg_image}" && convert -gaussian-blur 4x8 "${bg_image}" "${bg_image}" ;;
		pixelize) grim "${bg_image}" && convert "${bg_image}" -scale 10% -scale 1000% "${bg_image}" ;;
	esac

	if (( $# )); then
		convert -gravity center -composite -matte "${bg_image}" "$1" "${bg_image}"
	fi

	printf '%s' "${bg_image}"
}

main() {
	while (( $# )); do
		case "$1" in
			--help|-h) usage; return 0;;
			--mode|-m) mode="$2"; shift;;

			--) shift; break;;
			-*)
				err "Unknown key: $1"
				usage
				return 1
			;;

			*) break;;
		esac
		shift
	done

	#(( $# )) || {
		#usage
		#return 1
	#}

	[[ -d "${cfg_tmpdir}" ]] || {
		mkdir -p "${cfg_tmpdir}" || {
			return 1
		}
	}

	case "${mode:-pixelize}" in
		blur|pixelize) image=$( deskshot "$mode" );;
		rnd) image=$( random "$1" );;
		img) image="$1";;
		*) usage; return 1;;
	esac

	if [[ "${XDG_SESSION_TYPE}" == "wayland" ]]; then
		lock_cmd="swaylock -t -F --indicator-radius=100"
		if [[ "${image}" != "" ]]; then
			lock_cmd="${lock_cmd} -i '${image}'"
		fi
	else
		lock_cmd="i3lock -n -t -i '${image}'"
	fi

	until eval ${lock_cmd}; do
		true
	done
}

main "$@"
