#!/bin/bash

VPN_SYMBOL="\uf023"
SIZE="12"
ON_COLOR="green"
OFF_COLOR="#333333"

ip_route=$(ip route get 1)
is_tun=$(echo ${ip_route} | grep "tun0")
symbol=${VPN_SYMBOL}
color=${OFF_COLOR}

if [[ ! -z "${is_tun}" ]]; then
  symbol=${VPN_SYMBOL}
  color=${ON_COLOR}
fi

echo -e "<span font='${SIZE}' color='${color}'>${symbol}</span>"
echo -e "<span font='${SIZE}' color='${color}'>${symbol}</span>"
