#!/bin/bash

VPN_SYMBOL="\uf023"
SIZE="12"
ON_COLOR="green"
OFF_COLOR="#191919"
VPN_INTERFACE="/proc/sys/net/ipv4/conf/tun0"

symbol=${VPN_SYMBOL}
color=${OFF_COLOR}

if [[ -d "${VPN_INTERFACE}" ]]; then
  symbol=${VPN_SYMBOL}
  color=${ON_COLOR}
fi

echo -e "<span font='${SIZE}' color='${color}'>${symbol}</span>"
echo -e "<span font='${SIZE}' color='${color}'>${symbol}</span>"
